# Setup

# set -g prefix ^B

set -sg escape-time 0
set -g base-index 1
set -g history-limit 1000000
set -g status-position bottom

setw -g mode-keys vi

# List of plugins
# source-file ~/.tmux.plugins.conf

# move previous with Alt+h, next with Alt+l
bind -n M-h previous-window
bind -n M-l next-window

# Auto rename tabs
set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_path}'

setw -g window-status-current-format "#I:#{b:pane_current_path}#F"
setw -g window-status-format "#I:#{b:pane_current_path}#F"

# pi coding agent
set -g extended-keys on
set -g extended-keys-format csi-u
